### ISSUE TITLE
Concurrency

### ISSUE THREAD

**Issue by srivathsah** [bitlush/avl-tree-c-sharp#2]
Interesting implementation and I read through the blog post that covers this work. One question I had in mind and was not able to answer myself was how would the implementation handle concurrent inserts and searches . Where I am going at is, if there is way to handle concurrency using this strategy , then I would love to try this out in my next project. Without concurrency i don't see a real use case in production. BTW, I am currently using ImmutableDictionary for concurrent scenarios, although the performance is not the best, everything is deterministic about it, therefore debugging is easy

**Comment by bitlush** [comment]
This is not a concurrent AVL tree. Use ConcurrentDictionary which provides a fast lock-free implementation of a hashtable.

The AVL tree is thread safe for concurrent reads but is not designed for overlapping read/writes from multiple threads.

If you are light on writes but heavy on reads you could use a ReaderWriterLockSlim to make the AVL tree threadsafe in calling code.
